// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OHD.Data;

namespace OHD.Migrations
{
    [DbContext(typeof(ODHContext))]
    [Migration("20221214170401_first_migration_O")]
    partial class first_migration_O
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OHD.Models.IdentityRegistor", b =>
                {
                    b.Property<int>("IdentityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("identity_id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("IdentityName")
                        .HasColumnName("identity_name")
                        .HasColumnType("varchar(25)")
                        .HasMaxLength(25)
                        .IsUnicode(false);

                    b.HasKey("IdentityId")
                        .HasName("PK__identity__D51AF5F4DCA8EE34");

                    b.ToTable("identity_registor");
                });

            modelBuilder.Entity("OHD.Models.TblAssignbyAssignto", b =>
                {
                    b.Property<int>("ByToId")
                        .HasColumnName("by_to_id")
                        .HasColumnType("int");

                    b.Property<int?>("AssignbyId")
                        .HasColumnName("assignby_id")
                        .HasColumnType("int");

                    b.Property<int?>("AssigntoId")
                        .HasColumnName("assignto_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("AssignyDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("assigny_date")
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("ByToId")
                        .HasName("PK__tbl_assi__49C454DE88E84FCB");

                    b.HasIndex("AssignbyId");

                    b.HasIndex("AssigntoId");

                    b.ToTable("tbl_assignby_assignto");
                });

            modelBuilder.Entity("OHD.Models.TblAssignees", b =>
                {
                    b.Property<int>("AssiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("assi_id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AssiName")
                        .HasColumnName("assi_name")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.HasKey("AssiId")
                        .HasName("PK__tbl_assi__7333958E04AA1BBF");

                    b.ToTable("tbl_assignees");
                });

            modelBuilder.Entity("OHD.Models.TblComplaints", b =>
                {
                    b.Property<int>("CompId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("comp_id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CompAssiId")
                        .HasColumnName("comp_assi_id")
                        .HasColumnType("int");

                    b.Property<int?>("CompFacilitySelectedId")
                        .HasColumnName("comp_facilitySelected_Id")
                        .HasColumnType("int");

                    b.Property<int?>("CompIdentityId")
                        .HasColumnName("comp_identity_id")
                        .HasColumnType("int");

                    b.Property<string>("CompName")
                        .HasColumnName("comp_name")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<DateTime?>("CompRequestdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("comp_requestdate")
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CompStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("comp_status")
                        .HasColumnType("int")
                        .HasDefaultValueSql("((1))");

                    b.HasKey("CompId")
                        .HasName("PK__tbl_comp__531653DD0E7905B6");

                    b.HasIndex("CompAssiId");

                    b.HasIndex("CompFacilitySelectedId");

                    b.HasIndex("CompIdentityId");

                    b.ToTable("tbl_complaints");
                });

            modelBuilder.Entity("OHD.Models.TblFacilities", b =>
                {
                    b.Property<int>("FaciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("faci_id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FaciBrifedescription")
                        .HasColumnName("faci_brifedescription")
                        .HasColumnType("varchar(1200)")
                        .HasMaxLength(1200)
                        .IsUnicode(false);

                    b.Property<string>("FaciFacilities")
                        .HasColumnName("faci_facilities")
                        .HasColumnType("varchar(25)")
                        .HasMaxLength(25)
                        .IsUnicode(false);

                    b.HasKey("FaciId")
                        .HasName("PK__tbl_faci__D698B94277AF3BCC");

                    b.ToTable("tbl_facilities");
                });

            modelBuilder.Entity("OHD.Models.TblLab", b =>
                {
                    b.Property<int>("LabId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("lab_id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LabDescirption")
                        .HasColumnName("lab_descirption")
                        .HasColumnType("varchar(500)")
                        .HasMaxLength(500)
                        .IsUnicode(false);

                    b.Property<int?>("LabFacilityId")
                        .HasColumnName("lab_facility_id")
                        .HasColumnType("int");

                    b.Property<string>("LabName")
                        .HasColumnName("lab_name")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.HasKey("LabId")
                        .HasName("PK__tbl_lab__66DE64DBF0F4DAFF");

                    b.HasIndex("LabFacilityId");

                    b.ToTable("tbl_lab");
                });

            modelBuilder.Entity("OHD.Models.TblMaintaines", b =>
                {
                    b.Property<int>("MaintId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("maint_id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("MaintLabId")
                        .HasColumnName("maint_lab_id")
                        .HasColumnType("int");

                    b.Property<int?>("MaintStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("maint_status")
                        .HasColumnType("int")
                        .HasDefaultValueSql("((1))");

                    b.HasKey("MaintId")
                        .HasName("PK__tbl_main__56128A704B36B56A");

                    b.HasIndex("MaintLabId");

                    b.ToTable("tbl_maintaines");
                });

            modelBuilder.Entity("OHD.Models.TblStudentCouncil", b =>
                {
                    b.Property<int>("StuConsId")
                        .HasColumnName("stu_cons_id")
                        .HasColumnType("int");

                    b.Property<string>("StuConsName")
                        .HasColumnName("stu_cons_name")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<int?>("StuMaintaniesId")
                        .HasColumnName("stu_maintanies_id")
                        .HasColumnType("int");

                    b.HasKey("StuConsId")
                        .HasName("PK__tbl_stud__2D1C5666CFBE55DB");

                    b.HasIndex("StuMaintaniesId");

                    b.ToTable("tbl_student_council");
                });

            modelBuilder.Entity("OHD.Models.TblAssignbyAssignto", b =>
                {
                    b.HasOne("OHD.Models.TblAssignees", "Assignby")
                        .WithMany("TblAssignbyAssignto")
                        .HasForeignKey("AssignbyId")
                        .HasConstraintName("FK__tbl_assig__assig__3C69FB99");

                    b.HasOne("OHD.Models.IdentityRegistor", "Assignto")
                        .WithMany("TblAssignbyAssignto")
                        .HasForeignKey("AssigntoId")
                        .HasConstraintName("FK__tbl_assig__assig__3D5E1FD2");
                });

            modelBuilder.Entity("OHD.Models.TblComplaints", b =>
                {
                    b.HasOne("OHD.Models.TblAssignees", "CompAssi")
                        .WithMany("TblComplaints")
                        .HasForeignKey("CompAssiId")
                        .HasConstraintName("FK__tbl_compl__comp___44FF419A");

                    b.HasOne("OHD.Models.TblFacilities", "CompFacilitySelected")
                        .WithMany("TblComplaints")
                        .HasForeignKey("CompFacilitySelectedId")
                        .HasConstraintName("FK__tbl_compl__comp___4316F928");

                    b.HasOne("OHD.Models.IdentityRegistor", "CompIdentity")
                        .WithMany("TblComplaints")
                        .HasForeignKey("CompIdentityId")
                        .HasConstraintName("FK__tbl_compl__comp___440B1D61");
                });

            modelBuilder.Entity("OHD.Models.TblLab", b =>
                {
                    b.HasOne("OHD.Models.TblFacilities", "LabFacility")
                        .WithMany("TblLab")
                        .HasForeignKey("LabFacilityId")
                        .HasConstraintName("FK__tbl_lab__lab_fac__48CFD27E");
                });

            modelBuilder.Entity("OHD.Models.TblMaintaines", b =>
                {
                    b.HasOne("OHD.Models.TblLab", "MaintLab")
                        .WithMany("TblMaintaines")
                        .HasForeignKey("MaintLabId")
                        .HasConstraintName("FK__tbl_maint__maint__4BAC3F29");
                });

            modelBuilder.Entity("OHD.Models.TblStudentCouncil", b =>
                {
                    b.HasOne("OHD.Models.TblMaintaines", "StuMaintanies")
                        .WithMany("TblStudentCouncil")
                        .HasForeignKey("StuMaintaniesId")
                        .HasConstraintName("FK__tbl_stude__stu_m__4F7CD00D");
                });
#pragma warning restore 612, 618
        }
    }
}
